# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.load_file = QtWidgets.QPushButton(self.centralwidget)
        self.load_file.setGeometry(QtCore.QRect(20, 20, 100, 30))
        self.load_file.setObjectName('load_file')
        self.prev_page = QtWidgets.QPushButton(self.centralwidget)
        self.prev_page.setGeometry(QtCore.QRect(510, 20, 30, 30))
        self.prev_page.setObjectName('prev_page')
        self.next_page = QtWidgets.QPushButton(self.centralwidget)
        self.next_page.setGeometry(QtCore.QRect(550, 20, 30, 30))
        self.next_page.setObjectName('next_page')
        self.view_page = QtWidgets.QLabel(self.centralwidget)
        self.view_page.setGeometry(QtCore.QRect(20, 70, 561, 711))
        self.view_page.setText('')
        self.view_page.setAlignment(QtCore.Qt.AlignCenter)
        self.view_page.setObjectName('view_page')
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'MainWindow'))
        self.load_file.setText(_translate('MainWindow', 'Загрузить'))
        self.prev_page.setText(_translate('MainWindow', '<'))
        self.next_page.setText(_translate('MainWindow', '>'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
